# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c2cd311583c7bbbfcefba746270242b959b07232119706f6fa8242d76ebd74463f68410e7221bb0a651517f888e86e54bd6a4941584bda89aa3df22d1118407

test:
  secret_key_base: 5a55da22fa317f1c8bc6105f41b1a266a99cd579a8c31d6b281b923a3c0eb0e68ba92daaac751c9a1eeea19551c1742c2b6f56bbdc51789bb2da77afcaec4bf3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
